### ISSUE TITLE
Export / Minimal Notation Promotion

### ISSUE THREAD

**Issue by Alexbay218** [adri326/5dchess-notation#9]
Trying to implement minimal notation in 5d-chess-ts and noticed the lack of promotion indication. Easiest way to handle is to add promotion piece on the destination side (something like `(0T14)a7(0T14)Qa8`)

**Comment by adri326** [comment]
That's on me, indeed. I'd like to argue for adding it at the end instead, as that would make the minimal notation more compatible with the regular notation, though: `(0T14)a7(0T14)a8=Q`

**Comment by Alexbay218** [comment]
Minimal notation is already breaking several regular notation norms. I think it makes sense to add promotion as before physical destination coordinates to match the source coordinate piece letter.

**Comment by Alexbay218** [comment]
Redesigning a 5DPGN parser, and I retract my previous statement on the promotion indicator location. Setting it at the end is fine.
